### ISSUE TITLE
processfragments.js async broken

### ISSUE THREAD

**Issue by muteflamingo** [Fiddlekins/podbot#10]
processFragments.js on a valid folder gives ```

Q:\tdibot\podbot-master>node processFragments.js podcasts\349998842470727683-1516139564011
Q:\tdibot\podbot-master\processFragments.js:159
        fs.readdir(inputDirectory, async(err, files) => {
                                        ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9).
```. Any suggestions on fixing this?

**Comment by Fiddlekins** [comment]
You need to be running node 8 or higher, it's getting confused about the arrow function syntax

**Comment by muteflamingo** [comment]
now it says (node:23616) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'forEach' of undefined
(node:23616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. and exits.

**Comment by Fiddlekins** [comment]
I tweaked the error handling slightly.
Run it again and it should spit out something a bit more useful.
It looks like an invalid path again though

**Comment by muteflamingo** [comment]
it was the same problem, it assuming a leading podcasts/. another question, what format does it end up with?

**Comment by Fiddlekins** [comment]
Raw PCM data, 48K rate, dual channel, s16le encoded (signed 16bit little endian)
I use audacity to import the output, then export it as mp3
