### ISSUE TITLE
FFMpeg not found

### ISSUE THREAD

**Issue by Fysellynator** [Fiddlekins/podbot#20]
It keeps saying [ERROR] Error: FFMpeg not found

**Comment by muteflamingo** [comment]
Have you tried installing FFMPEG?

**Comment by Fysellynator** [comment]
Yes, but it still gives me the same error.

**Comment by Fiddlekins** [comment]
Podbot expects to be able to access ffmpeg globally - in other words, if you opened your terminal you should be able to type in `ffmpeg`, hit enter, and not get an error about it being a missing command.

If you've installed ffmpeg but cannot access it globally then you need to make sure the ffmpeg binary location is added to your path environment variable.

**Comment by Fysellynator** [comment]
How do I access it globally? I'm pretty new to all this stuff so... yeah... sorry.

**Comment by Fiddlekins** [comment]
Assuming you're on windows, the instructions for "part 2: Enabling FFmpeg in the Command Line" here https://www.wikihow.com/Install-FFmpeg-on-Windows should be able to guide you through the process.
Be careful not to delete pre-existing entries in the path variable, as you can cause existing programs to stop working properly by doing so.

Here's another link that will give a bit of a better understanding on what environment variables are and how to manipulate them: https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them

**Comment by Fysellynator** [comment]
After doing all this now it won't process when I type "npm run process". It just spits a really long error.

**Comment by Fiddlekins** [comment]
If you're on windows then sometimes messing with the path environment variable causes things that can normally be accessed through it to fail until you reboot, never figured out why.

If it persists after reboot then post the error and I'll figure out what's going on. Might be simpler to just hit me up on discord than post here, Fiddlekins#8295
