### ISSUE TITLE
>256MB

### ISSUE THREAD

**Issue by shikhir-arora** [Fiddlekins/podbot#7]
Hey, thanks for making this great bot! Works very well and as intended! 👍 

Node V8 has a limit of 256MB/buffer, so if the unprocessed strings go above this size, the decodeOpus.js will not work in the current form. I was wondering what you think is the best course of action; just warning users and stopping at 200MB with a new buffer, having multiple buffers after that (I manually cut a 318MB file I had and made sure to split it at the right point) -- or just use something like jsonify which may parse things better and allow for greater sizes. It doesn't look like Node is really designed to handle large buffers, which makes sense.

**Comment by Fiddlekins** [comment]
Huh, I had not considered this limitation.
I've updated it stream it in and processing it as it goes instead of loading it all in upfront.
I don't have large anything to test this with though, so let me know how it works.

**Comment by shikhir-arora** [comment]
Yes, everything works well, thanks for making that change so quickly. Verified with very large buffers and no issue. Thank you! 🙂

**Comment by Fiddlekins** [comment]
Perfect, glad to hear it.
