### ISSUE TITLE
decodeOpus on windows gives ENOENT

### ISSUE THREAD

**Issue by muteflamingo** [Fiddlekins/podbot#9]
when I pass a directory with the opus_string files, decodeOpus.js immediately says `Could not read input due to: Error: ENOENT: no such file or directory, scandir '(redacted)\podbot-master\podcasts\podcasts\349998842470727683-1516139564011'`. Is there any way to fix this?

**Comment by Fiddlekins** [comment]
Well, I can only assume you're passing it an invalid path or a path with special characters that cause problems.
Looking at the code, I guess a path with a space in would fail because it would be treated as multiple arguments rather than just one.

**Comment by muteflamingo** [comment]
Q:\tdibot\podbot-master\podcasts\podcasts\349998842470727683-1516139564011 doesn't have any special characters...

**Comment by Fiddlekins** [comment]
If you open up cmd and enter "cd Q:\tdibot\podbot-master\podcasts\podcasts\349998842470727683-1516139564011" what does it say?

**Comment by muteflamingo** [comment]
oh... the code wants 349998842470727683-1516139564011 instead of podcasts\349998842470727683-1516139564011. My mistake, sorry.

**Comment by Fiddlekins** [comment]
Oh shit, yeah, I totally forgot that
